- name: Stop experiment on router and download files
  hosts: router
  become: true
  tasks:
    - name: stop services
      ansible.builtin.shell: |
        killall tcpdump || true
      ignore_errors: yes

    - name: prepare results
      ansible.builtin.shell: |
        mv -f ~/tcp.pcap /home/ubuntu
        chown ubuntu:ubuntu /home/ubuntu/tcp.pcap
      ignore_errors: yes

    - name: download tcpdump
      become: false
      shell: |
        scp -F ./190n-inf-key/ssh_config router:/home/ubuntu/tcp.pcap "./tcp.pcap"
      args:
        chdir: "{{ playbook_dir }}/.."
      delegate_to: localhost
      ignore_errors: yes
